amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIAIOUN7QEVJPWFZYEA
  secretKey: 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
  bucketName: actent-res
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 469535828427-l1e7su82oc0bvirtdgmh26krf5p9kj5s.apps.googleusercontent.com
            clientSecret: 89I0VF570CgReRTHds5F39Zr
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 369144570610615
            clientSecret: 4eae1840b0ddd0bfa8092de02123cb59
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

